site_name: SY's TW Blog
site_url: https://schoi28.github.io/myBlog/
theme:
  name: material

# Copyright
copyright: Copyright &copy; 2024 Soyoon Choi

plugins:
  - blog:
      blog_toc: true

nav:
  - Blog:
    - blog/index.md